### ISSUE TITLE
Signature Of KeyValue:Batch:Set-Many

### ISSUE THREAD

**Issue by adamgfraser** [WebAssembly/wasi-keyvalue#22]
The current signature of `set-many` is as follows:

`set-many: func(bucket: bucket, keys: keys, values: list<tuple<key, outgoing-value>>) -> result<_, error>`

This seems strange because we are providing the keys twice, first as part of `keys` and second as part of the tuple in `values`. This seems like is creates a risk of inconsistency if `keys` and `values` have different keys. Can we just delete `keys` from the signature? Or are there some more complex expected semantics here like keys included in `keys` but not `values` are supposed to be deleted (and then what is supposed to happen to keys included in `values` but not `keys`?

**Comment by Mossaka** [comment]
Hey @adamgfraser thanks for raising this issue!

It indeed seems redundant to provide keys separately when they're also part of the values tuple. The risk of inconsistency is real: if a key appears in keys but not in values, or vice versa, it's ambiguous what the behavior should be.

I will have a PR to update the function signature.

**Comment by adamgfraser** [comment]
@Mossaka Thank you! 🙏
