### ISSUE TITLE
 Signature Of KeyValue::ReadWrite::Get

### ISSUE THREAD

**Issue by adamgfraser** [WebAssembly/wasi-keyvalue#24]
The current signature of `get` is:

```
get: func(bucket: bucket, key: key) -> result<incoming-value, error>
```

I would have expected the signature to be:

```
get: func(bucket: bucket, key: key) -> result<option<incoming-value>, error>
```

In the current signature, if a value does not exist this results in an error. This is somewhat subjective, but I would consider the possibility that a value does not exist for a key to be part of normal operation versus an error case (e.g. not being able to connect to the underlying data source) and would like it to be explicitly represented in the type signature.

This is especially true today because the error case is just basically a string so it is not possible for the user to introspect on the error and determine whether the value didn't exist or there was a runtime exception in a principled way. It sounds like there are plans to build out the error case and if it was an enumeration that included the value not being found then it would allow users to handle the possibility of a value not existing.

However, that still leaves implementers of the interface now in an awkward position and I tend to think that representing the optionality explicitly is the better API.

Would you consider a change for this?

**Comment by adamgfraser** [comment]
Similar comment applies to `get-many`.

The signature could go from:

```
get-many: func(bucket: bucket, keys: keys) -> result<list<incoming-value>, error>
```

to:

```
get-many: func(bucket: bucket, keys: keys) -> result<list<option<incoming-value>>, error>
```

**Comment by Mossaka** [comment]
Seems reasonable to me. @devigned what do you think?

**Comment by devigned** [comment]
I agree. Totally reasonable that there may not be a result due to the key not existing in the store.
