### ISSUE TITLE
Unsupported interfaces

### ISSUE THREAD

**Issue by lann** [WebAssembly/wasi-keyvalue#48]
If a runtime supports multiple KV backend implementations there may be some features that are only supported by some of those implementations (e.g. `atomics`, `watcher`). What should a runtime do if an application has imported one of these interfaces and then attempts to use it with a store that doesn't support that interface?

For example, let's say a guest app uses two stores: `transactions` and `cache`.
- For `transations` the application needs a durable store with atomic CAS so it imports `atomics` and uses an appropriate implementation for that store.
- For `cache` the application needs higher performance so it uses a different in-memory implementation which doesn't support atomics.
- Later in this application's development, a developer sees that the `atomics` interface is available and attempts to use it with the `cache` store. _What happens?_

**Comment by Mossaka** [comment]
> What should a runtime do if an application has imported one of these interfaces and then attempts to use it with a store that doesn't support that interface?

That's a great question, and your concern with an application that uses `atomic` runs on a platform that only provides `cache` is a valid question, though `wasi:keyvalue` current does not support a cache store. 

The runtime should detect that the store does not support the requested interface, which in this case is `atomics`, and either throw a descriptive error or provide a fallback mechanisms for graceful degradation.

**Comment by lann** [comment]
After some external discussion it does seem like "sorry atomics aren't supported" errors are probably the best we can do in the short term.
